name: qiniu_main

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.19]
    runs-on:  ${{ matrix.platform }}
    steps: 
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pwd
          go install https://github.com/qiniu/qshell@latest
          qshell account -- ${{ secrets.qiniu_AccessKey }} ${{ secrets.qiniu_SecretKey }} github
          qshell qupload2 --worker 10 --src-dir ./ --bucket ${{ secrets.qiniu_bucket }} --check_exists true --check_hash true --skip-suffixes ".github/,.git/" --skip_file_prefixes ".gitignore,.nojekyll" --success-list success.txt --failure-list failure.txt --overwrite-list overwrite.txt

      - name: echo log
        run: |
          echo "success file list:"
          cat success.txt
          echo "failure file list:"
          cat failure.txt
          echo "overwrite file list:"
          cat overwrite.txt
